# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1asLDEJBR5owx3-G2HH0gwiytNmnjBWOP
"""

Print

# prompt: Basic commands

print(10)
print("Hello")
print(10, "Hello")

a=input()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



